In [1]:
%pylab

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [2]:
a = arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
a.shape = 2,4
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
a.reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [22]:
a = arange(3)
shape(a)

(3,)

In [23]:
y = a[newaxis,newaxis,:]
shape(y)

(1, 1, 3)

In [25]:
a = arange(6)
a.shape = 2,1,3
b = a.squeeze()
b.shape

(2, 3)

In [26]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
b.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [28]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
x = array([[2,5,7],[3,8,1]])
y = array([[3,7,9],[7,1,3]])
z = array((x,y))#dstack((x,y))

array([[[2, 5, 7],
        [3, 8, 1]],

       [[3, 7, 9],
        [7, 1, 3]]])

In [33]:
vstack((x,y))

array([[2, 5, 7],
       [3, 8, 1],
       [3, 7, 9],
       [7, 1, 3]])

In [35]:
c = hstack((x,y))

In [36]:
c.flatten()

array([2, 5, 7, 3, 7, 9, 3, 8, 1, 7, 1, 3])

In [40]:
d = c.flat
d[0] = 3
c#是引用

array([[3, 5, 7, 3, 7, 9],
       [3, 8, 1, 7, 1, 3]])

In [45]:
cc = c.transpose()
e = cc.ravel()
e[0] = 0
cc[1,1] = 0
c[1,2] = 0
print(c)
print(cc)
print(e)

[[3 5 7 3 7 9]
 [3 0 0 7 1 3]]
[[3 3]
 [5 0]
 [7 0]
 [3 7]
 [7 1]
 [9 3]]
[0 3 5 1 7 1 3 7 7 1 9 3]
