In [1]:
import numpy as np

In [5]:
a = np.array([[1,2,3,4,],[2,3,4,5]])
a.sum()

24

In [6]:
np.sum(a)

24

In [8]:
a.sum(axis=0)

array([3, 5, 7, 9])

In [9]:
a.sum(axis=-1)

array([10, 14])

In [10]:
a.prod()

2880

In [11]:
np.prod(a,axis=0)

array([ 2,  6, 12, 20])

In [13]:
np.max(a)

5

In [14]:
np.min(a)

1

In [15]:
np.max(a,axis=0)

array([2, 3, 4, 5])

In [16]:
np.min(a,axis=-1)

array([1, 2])

In [17]:
a.argmin()

0

In [18]:
a.argmax()

7

In [19]:
a.mean()

3.0

In [21]:
a.mean(axis = 0)

array([ 1.5,  2.5,  3.5,  4.5])

In [22]:
a.mean(axis=-1)

array([ 2.5,  3.5])

In [23]:
a.std(axis=1)#标准差

array([ 1.11803399,  1.11803399])

In [24]:
a.var(axis=1)#方差

array([ 1.25,  1.25])

In [25]:
a.clip(2,5)

array([[2, 2, 3, 4],
       [2, 3, 4, 5]])

In [26]:
a.ptp(axis=1)

array([3, 3])

In [27]:
a.round()

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [28]:
a.round(decimals=1)

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])